# Default values for myservice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: us-west1-docker.pkg.dev/fluted-volt-428205-p7/chereddy/myservice
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: TAG

service:
  type: LoadBalancer
  port: 80


livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

